### ISSUE TITLE
HA 2023.6 beta: Unexpected error fetching Opower data: 'dict' object has no attribute 'discard'

### ISSUE THREAD

**Issue by pdawg17** [tronikos/opower-hacs#5]
I know I should expect issues with betas but just a heads up that I get this error once I updated to the HA June beta...don't know if it's due to HA updating to Python 3.11 or something else.

**Comment by tronikos** [comment]
Fixed in https://github.com/tronikos/opower-hacs/commit/5cc52ced31572be4267ab6a7758160f86c674a37
This was broken by https://github.com/home-assistant/core/pull/92095
_extract_metadata_and_discard_impossible_columns  expects types to be a set.
{} is an empty dict not a set, so I changed it to set()
